# Generated by Django 4.0 on 2021-12-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('ChartPlot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartplot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
